apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d2tmau0vf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d2tmau0vf-nodejs 
  name: d2tmau0vf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: d2tmau0vf-nodejs 
